{
 "title": "node-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"node_exporter:9100\"} - node_boot_time_seconds{instance=\"node_exporter:9100\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\", mode!=\"idle\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "Docker"
    }
   ]
  },
  {
   "title": "CPU utilization / container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) / on(instance) group_left sum(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "System total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "System used"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\".+\"})",
     "legendFormat": "Docker used"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"node_exporter:9100\", job=\"node_exporter\"} - node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\", job=\"node_exporter\"}) / node_memory_MemTotal_bytes{instance=\"node_exporter:9100\", job=\"node_exporter\"}",
     "legendFormat": "System % used"
    }
   ]
  },
  {
   "title": "Memory capacity / container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_working_set_bytes{name=~\".+\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Disk capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "System total - {{device}} - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"} - node_filesystem_avail_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "System used - {{device}} - {{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"} - node_filesystem_avail_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}) / node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "System % used"
    }
   ]
  },
  {
   "title": "Disk IO utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"node_exporter:9100\", device=\"mmcblk0p2\"}[$__rate_interval])",
     "legendFormat": "System - {{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"node_exporter:9100\", device=\"mmcblk0p2\"}[$__rate_interval])",
     "legendFormat": "System read - {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"node_exporter:9100\", device=\"mmcblk0p2\"}[$__rate_interval])",
     "legendFormat": "System write - {{device}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"node_exporter:9100\"}",
     "legendFormat": "Sensor - {{sensor}}"
    }
   ]
  },
  {
   "title": "Back-up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"node_exporter:9100\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=\"node_exporter:9100\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=\"node_exporter:9100\"}",
       "legendFormat": "Load 15m"
      }
     ]
    }
   ]
  }
 ]
}