version: '3'

volumes:
  volume_pihole:
    external: true

networks:
  bridge_dns_stack:
    name: bridge_dns_stack

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      - bridge_dns_stack
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8000:80/tcp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PIHOLE_DNS_: unbound#53
      DNSMASQ_LISTENING: all
      DNS_FQDN_REQUIRED: "true"
      DNS_BOGUS_PRIV: "true"
      DNSSEC: "true"
      REV_SERVER: "true"
      REV_SERVER_CIDR: "${local_network_cidr}"
      REV_SERVER_TARGET: "${local_network_gateway}"
      FTLCONF_LOCAL_IPV4: "${local_network_pihole}" # needed?
      WEBTHEME: default-darker
    volumes:
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - volume_pihole:/etc/pihole/

  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    hostname: unbound
    networks:
      - bridge_dns_stack
    expose:
      - 53/tcp
      - 53/udp
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    cap_add:
      - NET_ADMIN # needed?
