{
 "title": "node-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"node_exporter:9100\"} - node_boot_time_seconds{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\", mode!=\"idle\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "Average all cores"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"node_exporter:9100\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"node_exporter:9100\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"node_exporter:9100\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Disk IO utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"node_exporter:9100\", device=\"mmcblk0p2\"}[$__rate_interval])",
     "legendFormat": "Utilization - {{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"node_exporter:9100\", device=\"mmcblk0p2\"}[$__rate_interval])",
     "legendFormat": "Read - {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"node_exporter:9100\", device=\"mmcblk0p2\"}[$__rate_interval])",
     "legendFormat": "Write - {{device}}"
    }
   ]
  },
  {
   "title": "Disk capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "Total - {{device}} - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"} - node_filesystem_avail_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "Used - {{device}} - {{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"} - node_filesystem_avail_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}) / node_filesystem_size_bytes{instance=\"node_exporter:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "Percentage used"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"node_exporter:9100\", job=\"node_exporter\"} - node_memory_MemAvailable_bytes{instance=\"node_exporter:9100\", job=\"node_exporter\"}) / node_memory_MemTotal_bytes{instance=\"node_exporter:9100\", job=\"node_exporter\"}",
     "legendFormat": "Percentage used"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"node_exporter:9100\"}",
     "legendFormat": "Sensor - {{sensor}}"
    }
   ]
  }
 ]
}