{
 "title": "speedtest-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"speedtest-exporter:9798\"}",
     "legendFormat": "Download speed"
    }
   ]
  },
  {
   "title": "Ping & jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"speedtest-exporter:9798\"}",
     "legendFormat": "Ping"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"speedtest-exporter:9798\"}",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"speedtest-exporter:9798\"}",
     "legendFormat": "Upload speed"
    }
   ]
  }
 ]
}